"use client";
/* eslint-disable @next/next/no-img-element -- object URL previews are transient local files */
import { useEffect, useState } from "react";
import type { Detection, InventoryResult, ReviewItem } from "../../lib/identification/types.ts";
import { INVENTORY_CATEGORIES } from "../../lib/identification/validation.ts";

export default function IdentificationWorkspace({ onClose, onConfirmed }: { onClose: () => void; onConfirmed: (items: InventoryResult[]) => void }) {
  const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[items,setItems]=useState<ReviewItem[]>([]),[token,setToken]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  function choose(next:File|null){if(preview)URL.revokeObjectURL(preview);setFile(next);setPreview(next?URL.createObjectURL(next):"");setItems([]);setError("")}
  async function analyze(){if(!file)return;setBusy(true);setError("");try{const form=new FormData();form.set("image",file);const r=await fetch("/api/identify",{method:"POST",body:form});const data=await r.json() as {detections?:Detection[];token?:string;error?:string};if(!r.ok)throw new Error(data.error||"Identification failed");setToken(data.token||"");setItems((data.detections||[]).map((d,i)=>({...d,id:`d-${i}`,accepted:true,source:"gemini",detectedName:d.name,detectedModel:d.model})))}catch(e){setError(e instanceof Error?e.message:"Identification failed")}finally{setBusy(false)}}
  function patch(id:string,values:Partial<ReviewItem>){setItems(current=>current.map(item=>item.id===id?{...item,...values}:item))}
  function addManual(){setItems(current=>[...current,{id:crypto.randomUUID(),accepted:true,source:"manual",name:"",model:null,category:"Sensors",quantity:1,boundingBox:null,confidence:null,detectedName:null,detectedModel:null,visibleMarkings:[],alternatives:[],description:"Manually added after reviewing the photo.",tags:[]}])}
  async function confirm(){setBusy(true);setError("");try{const r=await fetch("/api/identify/confirm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,items})});const data=await r.json() as {inventory?:InventoryResult[];error?:string};if(!r.ok)throw new Error(data.error||"Confirmation failed");onConfirmed(data.inventory||[]);onClose()}catch(e){setError(e instanceof Error?e.message:"Confirmation failed")}finally{setBusy(false)}}
  const accepted=items.filter(i=>i.accepted&&i.name.trim());
  return <div className="identify-overlay" role="dialog" aria-modal="true" aria-labelledby="identify-title"><section className="identify-workspace"><header><div><p className="eyebrow">CAMERA IDENTIFICATION</p><h2 id="identify-title">Identify your components</h2></div><button className="close" onClick={onClose} aria-label="Close">×</button></header><p className="privacy-note">Images are sent to Gemini for identification and are not stored by Parts Cabinet.</p><div className="identify-columns"><div className="upload-pane"><label className="photo-drop"><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>choose(e.target.files?.[0]||null)}/>{preview?<img src={preview} alt="Components selected for identification"/>:<><strong>Take or choose a photo</strong><span>Place one or several parts on a clear, well-lit background.</span></>}</label><button className="submit" disabled={!file||busy} onClick={analyze}>{busy&&!items.length?"Analyzing…":"Analyze photo"}</button></div><div className="review-pane" aria-live="polite">{error&&<p className="identify-error">{error}</p>}{!items.length&&!error&&<div className="review-empty"><strong>Review before saving</strong><p>Gemini’s likely names, models and counts will appear here. You stay in control.</p></div>}{items.map((item,index)=><article className={`detection-row ${!item.accepted?"rejected":""}`} key={item.id}><div className="detection-heading"><strong>Component {index+1}</strong>{item.confidence!==null&&<span className={item.confidence<.7?"low-confidence":""}>{Math.round(item.confidence*100)}% likely</span>}</div><label>Name<input value={item.name} onChange={e=>patch(item.id,{name:e.target.value})}/></label><div className="form-row"><label>Model<input value={item.model||""} placeholder="Model unknown" onChange={e=>patch(item.id,{model:e.target.value||null})}/></label><label>Quantity<input type="number" min="1" max="999" value={item.quantity||""} onChange={e=>patch(item.id,{quantity:Number(e.target.value)})}/></label></div><label>Category<select value={item.category} onChange={e=>patch(item.id,{category:e.target.value})}>{INVENTORY_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label>{item.model===null&&<p className="model-warning">Exact model not visible — it will be saved as model unknown.</p>}<button className="reject-button" onClick={()=>patch(item.id,{accepted:!item.accepted})}>{item.accepted?"Reject detection":"Restore detection"}</button></article>)}{items.length>0&&<><button className="manual-button" onClick={addManual}>＋ Add a missed component</button><button className="confirm-button" disabled={!accepted.length||busy} onClick={confirm}>{busy?"Saving…":`Confirm and add ${accepted.length} item${accepted.length===1?"":"s"}`}</button></>}</div></div></section></div>;
}
