import type { ConfirmRequest, InventoryResult } from "./types.ts";
import { normalizeIdentity } from "./validation.ts";
import { verifyConfirmationToken } from "./tokens.ts";
type Statement={bind(...v:unknown[]):Statement;first<T=unknown>():Promise<T|null>;all<T=unknown>():Promise<{results:T[]}>};
export type D1Like={prepare(sql:string):Statement;batch(statements:Statement[]):Promise<unknown[]>};
export type ConfirmResult={scanId:string;inventory:InventoryResult[]};
async function hash(v:string){return Buffer.from(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v))).toString("hex")}
async function loadScan(scanId:string,db:D1Like):Promise<ConfirmResult>{const rows=await db.prepare("SELECT DISTINCT p.id,p.name,p.model,p.category,p.quantity,p.description,p.tags FROM inventory_parts p JOIN identification_events e ON e.inventory_part_id=p.id WHERE e.scan_id=?").bind(scanId).all<Omit<InventoryResult,"tags">&{tags:string}>();return{scanId,inventory:rows.results.map(r=>({...r,tags:JSON.parse(r.tags) as string[]}))}}
export async function confirmIdentification(input:ConfirmRequest,db:D1Like):Promise<ConfirmResult>{await verifyConfirmationToken(input.token);const tokenHash=await hash(input.token);const prior=await db.prepare("SELECT id FROM identification_scans WHERE confirmation_token_hash=?").bind(tokenHash).first<{id:string}>();if(prior)return loadScan(prior.id,db);const accepted=input.items.filter(i=>i.accepted),scanId=crypto.randomUUID();const q:Statement[]=[db.prepare("INSERT INTO identification_scans(id,confirmation_token_hash,user_id,provider,provider_model,accepted_detection_count) VALUES(?,?,NULL,'gemini',?,?)").bind(scanId,tokenHash,process.env.GEMINI_MODEL||"gemini-3.1-flash-lite",accepted.length)];for(const i of accepted){const n=normalizeIdentity(i.name),m=i.model?normalizeIdentity(i.model):"__unknown__",edited=i.source==="gemini"&&(normalizeIdentity(i.detectedName||"")!==n||normalizeIdentity(i.detectedModel||"")!==normalizeIdentity(i.model||""));q.push(db.prepare("INSERT INTO inventory_parts(id,name,normalized_name,model,model_key,category,quantity,description,tags) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(normalized_name,model_key) DO UPDATE SET quantity=quantity+excluded.quantity,name=excluded.name,category=excluded.category,description=excluded.description,tags=excluded.tags,updated_at=CURRENT_TIMESTAMP").bind(crypto.randomUUID(),i.name,n,i.model,m,i.category,i.quantity,i.description,JSON.stringify(i.tags)));q.push(db.prepare("INSERT INTO identification_events(id,scan_id,inventory_part_id,source,detected_name,detected_model,confirmed_name,confirmed_model,quantity_added,confidence,visible_markings,bounding_box,alternatives,was_edited) VALUES(?,?,(SELECT id FROM inventory_parts WHERE normalized_name=? AND model_key=?),?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),scanId,n,m,i.source,i.detectedName,i.detectedModel,i.name,i.model,i.quantity,i.confidence===null?null:Math.round(i.confidence*1000),JSON.stringify(i.visibleMarkings),i.boundingBox?JSON.stringify(i.boundingBox):null,JSON.stringify(i.alternatives),edited?1:0))}await db.batch(q);return loadScan(scanId,db)}
